### PR TITLE
fix(instagram): Fix black screen when sharing to Instagram Stories with a sticker

### PR DESCRIPTION
**Pull request by Sk92**
# Overview
Ciao! 👋🏻
I would like to improve the PR #1137 (related to #1084) to fix this issue also when the shares includes a sticker image (a png over the background).
The solution is the same implemented in #1137 but it is applied to the "stickerImage" param with the only one difference that a sticker is a png and not a jpg.

The issue is only on Android.

# Test Plan
Use the `Share.shareSingle` function with the `Share.Social.INSTAGRAM_STORIES` prop and a sticker image.
You can use this code below to reproduce the bug:
```
const shareOptions = {
      stickerImage: `data:image/png;base64,${base64Image}`,
      backgroundTopColor: '#15B9DD',
      backgroundBottomColor: '#063478',
      social: Share.Social.INSTAGRAM_STORIES,
};

await Share.shareSingle(shareOptions);
```

Before this fix you'll see only a black screen or the Instagram app that tries to start but immediately crashes.
For the screenshots you could refer to the ones attached to PR #1137

### CODE REVIEW

**Review by MateusAndrade — APPROVED** [review]
Ciao! 👋🏻 Nice catch, thanks for the help! 🚀

**Comment by MateusAndrade** [comment]
It looks like we are we a build error related to Flipper here. Did you get this at another library @mikehardy? 👀

**Review by mikehardy — CHANGES_REQUESTED** [review]
looks good to me - @MateusAndrade - when I `git cherry-pick a4c75c2763786ffb14580ba05b8dae844c06a26e` (this commit hash) on to the branch that updates the example #1141  that I just PR'd, this compiles fine and the example app runs.

I think the file type requirements (that sticker must be `image/png` and background must be `image/jpeg` needs a documentation update though. Otherwise we are handing a foot-gun to developers with no way to fix it except for code inspection deep in native java code...

**Comment by mikehardy** [comment]
#1141 just went green in CI, should merge that one, then if you merge this one it'll be fine

**Comment by MateusAndrade** [comment]
> looks good to me - @MateusAndrade - when I `git cherry-pick a4c75c2763786ffb14580ba05b8dae844c06a26e` (this commit hash) on to the branch that updates the example #1141 that I just PR'd, this compiles fine and the example app runs.
> 
> I think the file type requirements (that sticker must be `image/png` and background must be `image/jpeg`) needs a documentation update though. Otherwise we are handing a foot-gun to developers with no way to fix it except for code inspection deep in native java code...

Good catch! Do you need any help to update the docs @Sk92?

**Comment by MateusAndrade** [comment]
@mikehardy do you think we can go on with this?

**Comment by mikehardy** [comment]
Sure @MateusAndrade

**Pull request merged**
