### PR TITLE
chore(example): update example to rn66

### PR DESCRIPTION
**Pull request by mikehardy**
# Overview

fixes android build breaks (jcenter is super flaky now, react-native 66 doesn't need it anymore) and fixes ios build breaks (react-native < 0.64.2 does not even build on Xcode > 12.4)

# Test Plan

1. Run example app locally (`yarn && yarn start` in one terminal, `yarn start:android` and/or `yarn start:ios` in another terminal)
1. see the same build error seen in #1140 
1. use upgrade-helper to update from react-native 0.63.x to 0.66.x
1. re-run the example app locally, see it pass

### CODE REVIEW

**Comment by mikehardy** [comment]
There were still 2 things to fix it - one was an android cliPath item, and one was cocoapods out of date on CircleCI because we were using old Xcode issue - I just pushed fixes for them - circleci should go green on this one

**Comment by mikehardy** [comment]
:boom: 

image

**Review by MateusAndrade — APPROVED** [review]

**Comment by MateusAndrade** [comment]
Nice! I'm dealing with this JCenter problem right now. 😆 Thanks!!! 🚀

**Comment by mikehardy** [comment]
Yeah, I'm disappointed that they let the service degrade after they said they'd keep it up, but :shrug: 
If you update to react-native 0.65+ everything is fine, and they just merged react-native-macos from 0.64 to 0.66 so even macos dependencies don't have to hold you back now.
I still have one dependency in one project on jcenter but should be able to move it to jitpack...such a pain!

**Pull request merged**
