### PR TITLE
feat(ios): support added for instagram direct message

### PR DESCRIPTION
**Pull request by ArsalImam**
# Overview
Support added to launch Instagram DM if only text/plain information is received in options. 
Primarily focused to solve #1244 

# Test Plan
- Example is also updated with test implementation
- Testing video is attached,

https://user-images.githubusercontent.com/53432361/182483932-33aba222-4ae3-44b1-937d-2f5982db0107.MP4

### CODE REVIEW

**Comment by ArsalImam** [comment]
Reviewers, any thoughts on this?

**Review by MateusAndrade — APPROVED** [review]

**Comment by melvnl** [comment]
@ArsalImam @MateusAndrade hey, this is lit, but I have a question, is this mean the implementation for android is not available at the moment ?

**Comment by MateusAndrade** [comment]
> @ArsalImam @MateusAndrade hey, this is lit, but I have a question, is this mean the implementation for android is not available at the moment ?

Yes, AFAIK its only available for iOS. But I can help you if want to give it a try for Android. 😃

**Comment by gabrielfvf7** [comment]
@melvnl , you figure it out how to make this on Android?

**Comment by ArsalImam** [comment]
Yes , I did it in the past on android also. Will share a PR for that one too. @gabrielfvf7

**Comment by gabrielfvf7** [comment]
> Yes , I did it in the past on android also. Will share a PR for that one too. @gabrielfvf7 

Ok, let me know then when you open the PR

**Comment by melvnl** [comment]
> @melvnl , you figure it out how to make this on Android?

Yo, unfortunately , I haven't work on this yet :D . Let's wait for @ArsalImam PR, it will be really helpful sir

**Comment by gabrielfvf7** [comment]
@melvnl , i figured out how to do it, using this way on my code:
return share.toApplication({
    message: text,
    type: 'text',
    url: '',
    social: RNShare.Social.INSTAGRAM,
  });
  
  Then the Instagram DM's open and share the text i sent im message argument

**Pull request merged**
