### PR TITLE
Allow custom activity types to be specified inside activityItemSources

### PR DESCRIPTION
**Pull request by hieu9102002**
# Overview

A few applications' api do not allow for sending of both messages and url (E.g.: #280 #760 WhatsApp, Slack). When this happens, the app api randomly chooses either the message or the url to be shared to the application (for WhatsApp, the message is always prioritized over the url). We would like to specify which of the two to send for these type of application when calling Share.open using activityItemSources.

# Test Plan

Inside where I am calling Share.open, I can now specify the bundle to specifically tell share options what to send and what not to, instead of just using the default ActivityTypes.
```ts
const url = payload.url ?? '';
const message = payload.message ?? '';
const options: ShareOptions = Platform.select({
	ios: {
		activityItemSources: [
			{
				placeholderItem: { type: 'url', content: url },
				item: { default: { type: 'url', content: url } },
			},
			{
				placeholderItem: { type: 'text', content: message },
				item: {
					default: { type: 'text', content: message },
					'net.whatsapp.WhatsApp.ShareExtension': null,
				},
			},
		],
	},
	default: {
		...payload,
	},
});
```

To verify the change works, try sharing using WhatsApp, now only the url is sent, the message is not. For other app shares, both the url and the message is still sent.

### CODE REVIEW

**Review by mikehardy — APPROVED** [review]
Hmm - not sure *exactly* how it does that, but it's a non-breaking change that appears to be mostly just providing more information as a return value, can't see how that will cause active harm :shrug:

**Comment by mikehardy** [comment]
For the avoidance of doubt: this seems to  be iOS-only? You don't mention that but it appears to be the only affected platform.

**Comment by hieu9102002** [comment]
> Hmm - not sure exactly how it does that

At the moment, if you specify an activity that is not in the list of default UI Activity items, say `net.whatsapp.WhatsApp.ShareExtension` inside my code snippet for example, it will be ignored. By making the change from returning nil if the users' provided activity items is not in the list of defaults to returning itself, it allows the UI activity view controller to attempt to find the share bundle the users' requested and make specific changes to that bundle. In this example, for every application but the one with the bundle name `net.whatsapp.WhatsApp.ShareExtension`, both the url and the message will be shared, but for WhatsApp sharing, it will only send the url and not the message, similarly to the example in [the docs](https://react-native-share.github.io/react-native-share/docs/share-open/#activityitemsources-ios-only), but instead of working for the messages app, it works for WhatsApp.

The system already have checks against bad input, so in case users input a share bundle name that does not exist, it will treat that as basically nil, so this change is non-breaking.

> For the avoidance of doubt: this seems to be iOS-only? You don't mention that but it appears to be the only affected platform.

Yes. UI Activity items are ios-only.

@mikehardy Hopefully my answer was detailed enough, please let me know if anything is still unclear.

**Pull request merged**
