### PR TITLE
Add Android GenericSingleShare And WeChat 

### PR DESCRIPTION
**Pull request by outofmemory**
# Overview
#950 

# Test Plan
test code add to example already ...

### CODE REVIEW

**Comment by outofmemory** [comment]
@MateusAndrade

**Comment by KingAmo** [comment]
why this pr is closed ?  any help please?

**Comment by mikehardy** [comment]
@KingAmo because it went stale. No one appeared to care.

Looks like you care though! Perhaps if you pulled the code in this PR and built + ran + tested it then confirmed it worked we could reopen and merge it?

**Comment by KingAmo** [comment]
> @KingAmo because it went stale. No one appeared to care.
> 
> Looks like you care though! Perhaps if you pulled the code in this PR and built + ran + tested it then confirmed it worked we could reopen and merge it?

thanks, i will test is this weekend and report it here

**Pull request closed without merging**
