### PR TITLE
fix(ios): use https in place of https for facebook/instagram/whatsapp

### PR DESCRIPTION
**Pull request by AliHaidar110**
# Overview

simple change to the URL schema of Facebook, Instagram, and Whatsapp

# Test Plan

Manually tested on **Pixel_4_API_30 simulator**.
_PS: No physical iPhone to test on_

### CODE REVIEW

**Comment by mikehardy** [comment]
Thank you - I really appreciate it. Testing is usually most of the work unfortunately, especially for the small changes - but it's vital. Cheers

**Comment by AliHaidar110** [comment]
> Thank you - I really appreciate it. Testing is usually most of the work unfortunately, especially for the small changes - but it's vital. Cheers

I am not that experienced. I did manual testing on Android for the three changed functions. If more is needed please tell me.

**Review by mikehardy — APPROVED** [review]
> I am not that experienced

That's okay, no one starts out experienced. You're trying (which I really appreciate), and hey, now you have more experience :-)

> I did manual testing on Android for the three changed functions. If more is needed please tell me.

I'm curious if you tested iOS - these changes are all to iOS files, so testing Android is testing lines that were not affected

That said, I copy-pasted the URLs and they all opened the valid pages I was expecting so I can't see how this can be wrong really ? Seems good to merge ...

**Comment by AliHaidar110** [comment]
> > I am not that experienced
> 
> That's okay, no one starts out experienced. You're trying (which I really appreciate), and hey, now you have more experience :-)
> 
> > I did manual testing on Android for the three changed functions. If more is needed please tell me.
> 
> I'm curious if you tested iOS - these changes are all to iOS files, so testing Android is testing lines that were not affected
> 
> That said, I copy-pasted the URLs and they all opened the valid pages I was expecting so I can't see how this can be wrong really ? Seems good to merge ...

thank you for the encouraging words. I could not test IOS because I don't have a device to test on.

**Comment by mikehardy** [comment]
"You might like" --> https://github.com/kholia/OSX-KVM, I use VMs for most of my macOS development verification, sitting on top of Ubuntu. The iOS Simulator works fine for almost all testing except that involving remote messaging (Simulators do not receive APNs messaging). I also have mac machines but the VMs are more convenient in combo with VSCode using remote-ssh connections to the VMs because I can also run windows VMs, or dual-boot to windows. Cheers

**Comment by MateusAndrade** [comment]
> "You might like" --> https://github.com/kholia/OSX-KVM, I use VMs for most of my macOS development verification, sitting on top of Ubuntu. The iOS Simulator works fine for almost all testing except that involving remote messaging (Simulators do not receive APNs messaging). I also have mac machines but the VMs are more convenient in combo with VSCode using remote-ssh connections to the VMs because I can also run windows VMs, or dual-boot to windows. Cheers

WOW! This is interesting, thanks for sharing @mikehardy! ❤️

**Pull request merged**
