### PR TITLE
fix(android): prevent implicit PendingIntent vulnerability

### LINKED ISSUE #1043: Google play console rejected, PendingIntent issue
### Steps to reproduce
1. Install react-native-share
2. Submit app to google play console

### Expected behaviour
Google Play should accept the app

### Actual behaviour
Google play reject because of pendingIntent issue

Screen Shot 2021-06-23 at 08 29 34

I found this when I search my entire node modules on TargetChosenReceiver.java

```       
 final PendingIntent callback = PendingIntent.getBroadcast(reactContext, 0, intent,
 PendingIntent.FLAG_CANCEL_CURRENT | PendingIntent.FLAG_ONE_SHOT);
```

This is what google suggest

https://support.google.com/faqs/answer/10437428

### Environment
- **React Native version**: 0.61.5

### react-native-share
**Version**: "^2.0.0"

### PR DESCRIPTION
**Pull request by mussegam**
# Overview

Google Play rejects apps using this library because of an Implicit PendingIntent Vulnerability: https://support.google.com/faqs/answer/10437428

This PR should fix #1043

# Test Plan

Verified that the sharing functionality works in my Android app with this fix

### CODE REVIEW

**Comment by MateusAndrade** [comment]
Nice! Did you manage to submit your app to Google Play with this fix?

**Comment by mussegam** [comment]
> Nice! Did you manage to submit your app to Google Play with this fix?

It's still in review, but at least they haven't complained about it yet. Will update as soon as I have more info :)

**Review by KencyK — APPROVED** [review]

**Comment by MateusAndrade** [comment]
> > Nice! Did you manage to submit your app to Google Play with this fix?
> 
> It's still in review, but at least they haven't complained about it yet. Will update as soon as I have more info :)

Thanks for the feedback! We can proceed with this merge as soon as you got a response from Google. 🚀

**Review by MateusAndrade — APPROVED** [review]

**Comment by mussegam** [comment]
Sorry it took so long, we had some unrelated issues with the release. 
The version that includes this fix has been reviewed and is now available in production 💪

**Pull request merged**
