### PR TITLE
Fixed getDataColumn not handling exception thrown by cursor.getColumn…

### PR DESCRIPTION
**Pull request by DylanJCraggs**
…IndexOrThrow

# Overview

# Test Plan

### CODE REVIEW

**Comment by DylanJCraggs** [comment]
An exception was being thrown attempting to open .msg file in Android which prevented the bottom sheet from opening.

This fix catches the exception and now displays the app sheet as expected.

**Comment by MateusAndrade** [comment]
Could you share the details about this exception and how to reproduce it?

**Comment by DylanJCraggs** [comment]
> Could you share the details about this exception and how to reproduce it?

@MateusAndrade 

Using Android 13, call Share.Open like below for a .msg file.

Share.open({
    url: fileUri, // make this a .msg file
    failOnCancel: false,
    filename: fileName,
    showAppsToView: true
});

**Review by MateusAndrade — APPROVED** [review]

**Pull request merged**
