### PR TITLE
added single share feature for telegram

### PR DESCRIPTION
**Pull request by harish92**
# Overview

# Test Plan

### CODE REVIEW

**Review by mikehardy — CHANGES_REQUESTED** [review]
Hi there! Very cool.

Seems like this needs a related documentation update https://github.com/react-native-share/react-native-share/blob/master/website/docs/share-single.mdx#supported-applications

Any plans on implementing iOS so it's cross-platform?

**Comment by harish92** [comment]
Thanks, 
Sorry, no plans yet implementing on IOS. Sure will do it in the future.

**Review by mikehardy — APPROVED** [review]
Looks good to me - and re: iOS, adding support there would be fabulous but I am always a fan of incremental progress (as long as limitations are documented, which they are now - thank you!) so that wouldn't stop me from merging. @MateusAndrade should hit the merge button though I think lest I have missed something

**Comment by MateusAndrade** [comment]
Nice! Everything looks great. Thanks a lot @harish92! 🚀

**Pull request merged**
