### PR TITLE
title is optional as per documentation

### PR DESCRIPTION
**Pull request by petrbela**

### CODE REVIEW

**Comment by mikehardy** [comment]
Just out of curiosity since this formally makes all items optional, are there cases where they are indeed non-optional? Are those cases validated in any way? (like with a sub-type for this thing or the other thing, where it is no longer optional?)

**Comment by petrbela** [comment]
Actually, it should only be optional in the `ShareSingle` interface. I'll fix it.

**Review by mikehardy — APPROVED** [review]
works for me, thanks for the extra info

**Comment by petrbela** [comment]
@demedos I think it might be optional but I'm not using it so didn't have enough data to propose that change (I'm not a maintainer). I suggest you create another PR with appropriate changes if you think that's how it should be.

**Comment by demedos** [comment]
done. see https://github.com/react-native-share/react-native-share/pull/1110

**Pull request merged**
