### PR TITLE
Fixed Twitter shareSingle with image on iOS

### PR DESCRIPTION
**Pull request by geroale**
# Overview
With this PR, Twitter shareSingle with image works on iOS.
Without this, shareSingle will copy the image url as a string in the Twitter card message.

### CODE REVIEW

**Comment by geroale** [comment]
This should improve the issues https://github.com/react-native-share/react-native-share/issues/1154 and https://github.com/react-native-share/react-native-share/issues/1285

**Review by mikehardy — COMMENTED** [review]
I don't personally use this feature so I'm inclined to trust the submitter based on their testing

I am curious how #1120 worked previously, and / or if this is a regression when using a generic share on non-twitter URLs? :thinking: it appears that prior to this change, this code block would execute for any open-able URL that was not twitter service-type, now it is only executing if it is twitter service type, regardless of open-able or not.

What will happen to non-twitter / open-able URLs now?

**Comment by geroale** [comment]
@mikehardy This is working for our use case: we have all the types of social share, including the generic `Share.open(...)` to share an image.

We should get a better answer and opinion from someone who worked at that part of the code.

That line of code, which is broken now, comes from the commits https://github.com/react-native-share/react-native-share/commit/add6613e89d80855843bf50591c5a232c68e3316 and https://github.com/react-native-share/react-native-share/commit/3bccd59faa392293d0e5ed7a29533fb80ba016c0

Then we should ask @oamado, @MateusAndrade, @IbrahimSulai or @mikehardy if they can help us.

**Comment by danielprrazevedo** [comment]
I was also having problems with sharing to twitter on ios, as soon as I installed the package through PR this was resolved.
```sh
npm install react-native-share/react-native-share#pull/1315/head
```
In my app I use sharing on twitter and instagram and both are still OK

**Review by mikehardy — APPROVED** [review]
LGTM I suppose :smile:

**Comment by MateusAndrade** [comment]
@geroale would you mind updating your branch? 😃

**Review by MateusAndrade — APPROVED** [review]

**Comment by geroale** [comment]
@MateusAndrade Yeah but once it is released on NPM I will delete my fork directly.

**Comment by MateusAndrade** [comment]
> @MateusAndrade Yeah but once it is released on NPM I will delete my fork directly.

Sure, no problem!

**Comment by geroale** [comment]
@MateusAndrade Alright, got it! It should be updated now

**Comment by BuddyMuhammad** [comment]
@MateusAndrade @mikehardy @jgcmarins 

It seems that in this PR, you have made changes to the way apps are opened directly. Previously, the code `[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]` was used to verify if a specific URL could be opened using the app, and then the library would proceed to open the target app. However, it appears that now the code only attempts to open Twitter, while other URLs are being opened in the browser.

**Comment by BuddyMuhammad** [comment]
@MateusAndrade @mikehardy @jgcmarins 

@geroale  It seems that in this PR, you have made changes to the way that twitter app should opened directly. Previously, the code `[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]` was used to verify if a specific URL could be opened using the app, and then the library would proceed to open the target app. However, it appears that now the code only attempts to open Twitter, while other URLs are being opened in the browser.

**Comment by MateusAndrade** [comment]
> @MateusAndrade @mikehardy @jgcmarins
> 
> @geroale It seems that in this PR, you have made changes to the way that twitter app should opened directly. Previously, the code `[[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:inAppBaseUrl]]` was used to verify if a specific URL could be opened using the app, and then the library would proceed to open the target app. However, it appears that now the code only attempts to open Twitter, while other URLs are being opened in the browser.

I see, could you confirm if this happened with a previous version?

**Comment by igorkirnbb** [comment]
Hello guys, we experience issues with shareSingle for Facebook because of this PR. It seems like now the app tries to open php link for Facebook share because `IF` equals `false` but then php link doesnt work. We had to patch library and remove IF/ELSE logic completely. May I ask why the code has those php links because it seems to work fine without them? 

Our patch for GenericShare.m:
```
//
//  GenericShare.m
//  RNShare
//
//  Created by Diseño Uno BBCL on 23-07-16.
//  Copyright © 2016 Facebook. All rights reserved.
//

#import "GenericShare.h"

@implementation GenericShare
    RCT_EXPORT_MODULE();
- (void)shareSingle:(NSDictionary *)options
    failureCallback:(RCTResponseErrorBlock)failureCallback
    successCallback:(RCTResponseSenderBlock)successCallback
    serviceType:(NSString*)serviceType
    inAppBaseUrl:(NSString *)inAppBaseUrl {

    NSLog(@"Try open view");

    SLComposeViewController *composeController = [SLComposeViewController  composeViewControllerForServiceType:serviceType];

    NSURL *URL = [RCTConvert NSURL:options[@"url"]];
    if (URL) {
        if (URL.fileURL || [URL.scheme.lowercaseString isEqualToString:@"data"]) {
            NSError *error;
            NSData *data = [NSData dataWithContentsOfURL:URL
                                    options:(NSDataReadingOptions)0
                                    error:&error];
            if (!data) {
                failureCallback(error);
                return;
            }
            UIImage *image = [UIImage imageWithData: data];
            [composeController addImage:image];

        } else {
            [composeController addURL:URL];
        }
    }

    if ([options objectForKey:@"message"] && [options objectForKey:@"message"] != [NSNull null]) {
        NSString *text = [RCTConvert NSString:options[@"message"]];
        [composeController setInitialText:text];
    }


    UIViewController *ctrl = RCTPresentedViewController();
    [ctrl presentViewController:composeController animated:YES completion:Nil];
    successCallback(@[@true, @""]);
  }

  @end
```

The patch was tested on latest iOS (real device) with jpeg image in Instagram, Twitter and Facebook.

I can also confirm that app release with `react-native-share` v8.0.0 works fine in production, so the issue started in newer versions. @MateusAndrade

**Comment by MateusAndrade** [comment]
> The patch was tested on latest iOS (real device) with jpeg image in Instagram, Twitter and Facebook.

> I can also confirm that app release with react-native-share v8.0.0 works fine in production, so the issue started in newer versions. @MateusAndrade

I see, I guess we will need to ever this and push a new version.

**Comment by igorkirnbb** [comment]
@MateusAndrade There is also seems to be a bug with IG sharing. For some reason it couldnt detect that we are sending JPG image, so it always showed latest image from phone gallery and not the one from url. We had to make another patch, this time in `RNShare.m` for `instagram`:
```
-            if([self isImageMimeType:options[@"url"]]) {// Condition to handle image
-                [shareCtl shareSingleImage:options failureCallback: failureCallback successCallback: successCallback];
-            } else {
-                [shareCtl shareSingle:options failureCallback: failureCallback successCallback: successCallback];
-            }
+            [shareCtl shareSingleImage:options failureCallback: failureCallback successCallback: successCallback];
```
Ofc this patch wont work for the videos but it seems to fix images. Example of image URL: `/var/mobile/Containers/Data/Application/08E31E6D-D5A2-44E2-8B65-02FC336AE39E/Library/Caches/DFCE34B9-079C-4F55-ABF1-102442C53AB5.jpg`. IG works perfectly fine with those images but lib couldnt detect them for `shareSingleImage`.

**Comment by igorkirnbb** [comment]
It also possible that all bugs are because of RN (0.71.7) because our prod on 0.70.6. We tried `react-native-share` v8.0.0 on 0.71.7 and it created similar bugs. But its interesting because there are issues from people who reporting same bugs on 0.60 RN I think..

Also on 0.71.7 the base64 started crashing app if we use `open` method. It worked fine on 8.0.0/0.70.6 but now we had to switch fully on jpg on iOS.

**Pull request merged**
