### PR TITLE
feat (android): add support to Instagram Stories video sharing

### LINKED ISSUE #907: Can't share instagram video story on Android
Hi, I am trying to share a video on Instagram story.
iOS working as expected, but on Android it doesn't work.

```
 const cache = await RNFetchBlob.config({
      fileCache: true,
      appendExt: 'mp4',
    }).fetch('GET', 'https://www.w3schools.com/html/mov_bbb.mp4', {});

    await InstaShare.shareSingle({
      social: InstaShare.Social.INSTAGRAM_STORIES,
      method: InstaShare.InstagramStories.SHARE_BACKGROUND_VIDEO,
      backgroundVideo: cache.path(),
      ...Platform.select({
        android: {
          forceDialog: true,
        },
      }),
    });
```

The error I get on Android - 

2020-11-08 12:35:56.759 17348-20900/com.test I/System.out: SHARE SINGLE METHOD
2020-11-08 12:35:56.759 17348-20900/com.test I/System.out: com.instagram.android
2020-11-08 12:35:56.771 17348-20900/com.test I/System.out: INSTALLED
2020-11-08 12:35:56.771 17348-20900/com.test I/System.out: ERROR Unknown Instagram stories sharing mode: shareBackgroundVideo
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out: java.lang.IllegalStateException: Unknown Instagram stories sharing mode: shareBackgroundVideo
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.social.ShareIntent.open(ShareIntent.java:213)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.social.SingleShareIntent.open(SingleShareIntent.java:40)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.social.InstagramStoriesShare.open(InstagramStoriesShare.java:27)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at cl.json.RNShareModule.shareSingle(RNShareModule.java:158)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at java.lang.reflect.Method.invoke(Native Method)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at android.os.Handler.handleCallback(Handler.java:883)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-11-08 12:35:56.772 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
2020-11-08 12:35:56.773 17348-20900/com.test I/System.out:     at android.os.Looper.loop(Looper.java:237)
2020-11-08 12:35:56.773 17348-20900/com.test I/System.out:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
2020-11-08 12:35:56.773 17348-20900/com.test I/System.out:     at java.lang.Thread.run(Thread.java:919)

### PR DESCRIPTION
**Pull request by kaioduarte**
# Overview
Background video assets currently is only available for iOS, this PR aims to add support for Android as well.

- Fixes #907 

# Test Plan
<details>

<summary>Minimal example</summary>

```js
import React from 'react';
import {StyleSheet, View, Button} from 'react-native';

import RNFetchBlob from 'rn-fetch-blob';
import Share from 'react-native-share';

const App = () => {
  const share = async () => {
    try {
      const cache = await RNFetchBlob.config({
        fileCache: true,
        appendExt: 'mp4',
      }).fetch('GET', 'https://www.w3schools.com/html/mov_bbb.mp4');

      await Share.shareSingle({
        social: Share.Social.INSTAGRAM_STORIES,
        method: Share.InstagramStories.SHARE_BACKGROUND_VIDEO,
        backgroundVideo: `file://${cache.path()}`,
      });
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <View style={styles.container}>
      <Button title="Share Video" onPress={share} />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});

export default App;
```
</details>

### Example

https://user-images.githubusercontent.com/11046907/102808928-082b5380-43b9-11eb-84de-34b7d68b1dab.mp4

### CODE REVIEW

**Review by MateusAndrade — APPROVED** [review]
Thanks, @kaioduarte! 🚀 🚀 🚀

**Comment by EstebanFuentealba** [comment]
Hi, @MateusAndrade @kaioduarte  I think you should not add provider logic to the generic class (ShareIntent.java). for that I should extend the class and add another social item

and override the "open" method and add that logic like

```java
// ...
public class InstagramStoriesShare extends SingleShareIntent {
// ...
    @Override
    public void open(ReadableMap options) throws ActivityNotFoundException {
        super.open(options);
        //  extra params here
        if (ShareIntent.hasValidKey("method", options)) {
                String method = options.getString("method");
                switch (method) {
                    case "shareBackgroundVideo": {
                    // ...
                    }
                    case "shareBackgroundImage": {
                    // ...
                    }
                    case "shareStickerImage": {
                    // ...
                    }
                    case "shareBackgroundAndStickerImage": {
                    // ...
                    }
                }
        }
        this.openIntentChooser(options);
    }
}
```
Gracias por compartir y aportar!

Saludos!

**Comment by MateusAndrade** [comment]
> Hi, @MateusAndrade @kaioduarte  I think you should not add provider logic to the generic class (ShareIntent.java). for that I should extend the class and add another social item
> 
> and override the "open" method and add that logic like
> 
> ```java
> // ...
> public class InstagramStoriesShare extends SingleShareIntent {
> // ...
>     @Override
>     public void open(ReadableMap options) throws ActivityNotFoundException {
>         super.open(options);
>         //  extra params here
>         if (ShareIntent.hasValidKey("method", options)) {
>                 String method = options.getString("method");
>                 switch (method) {
>                     case "shareBackgroundVideo": {
>                     // ...
>                     }
>                     case "shareBackgroundImage": {
>                     // ...
>                     }
>                     case "shareStickerImage": {
>                     // ...
>                     }
>                     case "shareBackgroundAndStickerImage": {
>                     // ...
>                     }
>                 }
>         }
>         this.openIntentChooser(options);
>     }
> }
> ```
> Gracias por compartir y aportar!
> 
> Saludos!

Nice suggestion, do you think we can go on with that @kaioduarte ?

**Comment by kaioduarte** [comment]
So we thought the same, @EstebanFuentealba!

I'm implementing `FacebookStories` right now and I already moved the logic to the provider. @MateusAndrade after that I can refactor the `InstagramStories` provider 😉.

Thanks guys.

**Comment by Lg0gs** [comment]
@kaioduarte 
Which version are you using?

**Comment by kaioduarte** [comment]
> @kaioduarte 
> Which version are you using?

Do you mean the Android version? It's 11.

**Pull request merged**
