### PR TITLE
[IOS] Support filename/filenames

### PR DESCRIPTION
**Pull request by linhvovan29546**
# Overview
[IOS]  `saveToFiles` don't allow custom filename. This PR allow custom `filename`.

# Test Plan
Tested on my device.
image
This is my screenshots
image

### CODE REVIEW

**Review by MateusAndrade — COMMENTED** [review]
Can we update the docs with this information as well?

**Comment by linhvovan29546** [comment]
@MateusAndrade yeah, i see a props `urls`, it allow saving multiple files. So I will make this PR to allow saving those files with different filenames, what do you think?

**Comment by linhvovan29546** [comment]
Hi @MateusAndrade , i just updated PR to support for `filenames`.

**Comment by Rohphi** [comment]
Any chance that this PR gets merged?

**Comment by MateusAndrade** [comment]
> Any chance that this PR gets merged?

Niceee! It looks like there is a conflict with `RNShare.m`, do you need help to fix this?

**Comment by linhvovan29546** [comment]
I just synced new code to my PR

**Review by MateusAndrade — APPROVED** [review]

**Pull request merged**
