### PR TITLE
fix(ios): import from codegen with RN 0.75+

### PR DESCRIPTION
**Pull request by huextrat**
# Overview

fixes: https://github.com/react-native-share/react-native-share/issues/1568

# Test Plan

### CODE REVIEW

**Review by MateusAndrade — APPROVED** [review]

**Comment by huextrat** [comment]
@MateusAndrade I haven't tested it on RN 0.74 with new arch but this change may break the old RN versions on the new arch

**Comment by MateusAndrade** [comment]
> @MateusAndrade I haven't tested it on RN 0.74 with new arch but this change may break the old RN versions on the new arch

I see, we can release a new major release. It looks like the pipeline for iOS is not working. 🤔

**Comment by huextrat** [comment]
I don't know if it's related, it fails as soon as the job starts

`ios_build` job seems to also be on failure on previous PRs. Something related to CircleCI config ?

**Comment by MateusAndrade** [comment]
> I don't know if it's related, it fails as soon as the job starts
> 
> `ios_build` job seems to also be on failure on previous PRs. Something related to CircleCI config ?

I see, it's related to the resource class used. I can fix this with another PR.

**Comment by efstathiosntonas** [comment]
hey folks, I believe it needs double quotes instead of brackets, at least this is what Xcode is complaining about.

ie. `#import <RNShareSpec.h>` -> `#import "RNShareSpec.h"`

Screenshot 2024-09-02 at 15 20 33

**Comment by huextrat** [comment]
Indeed! https://github.com/react-native-share/react-native-share/pull/1570

**Comment by benji-jo** [comment]
Appeared again in version 0.76.3

**Review by saadlatif75 — COMMENTED** [review]
yes this commit woiking fine...

**Pull request merged**
